source "http://rubygems.org"
gem "sinatra", "~>1.0"
gem "rake", "~>0.8.7"
gem "json", "~>1.4.6"

gem "sqlite3-ruby", "~>1.3.1"
gem "sequel", "~>3.14.0"
gem "sinatra-sequel", "~>0.9.0"

group :server do
	gem "thin"
end
